on: [push, pull_request]
name: Refactor code
jobs:
  rector:
    name: Rector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rector
        uses: zingimmick/rector-action@0.1.0
        with:
          args: --dry-run
